import { NextResponse } from "next/server";
import { RANGE_DATA, type DashRange } from "@/lib/data";
import type { AiInsight } from "@/lib/types";
import { geminiConfigured, generateJson } from "@/lib/ai/gemini";
import { igConfigured, fetchInstagramSnapshot } from "@/lib/instagram";

// AI weekly insight digest (PRD §6.2).
// Data source priority: live Instagram (if connected) -> sample fixtures.
// Generated by Gemini, with the sample insight as a graceful fallback.

const SCHEMA = {
  type: "object",
  properties: {
    summary: { type: "string" },
    observations: { type: "array", items: { type: "string" } },
    pattern: { type: "string" },
    action: { type: "string" },
    watchMetric: { type: "string" },
  },
  required: ["summary", "observations", "pattern", "action", "watchMetric"],
};

const SYSTEM =
  "You are the analytics advisor for Legali AI, a legal technology company. " +
  "Write in a direct, data-driven, actionable tone for the CEO. " +
  "Reference specific numbers and dates from the data provided. No generic advice — " +
  "every claim must trace to a number in the data.";

export async function POST(req: Request) {
  const { range = "30d" } = await req
    .json()
    .catch(() => ({}) as { range?: string });
  const rd = RANGE_DATA[range as DashRange] ?? RANGE_DATA["30d"];

  if (!geminiConfigured()) {
    return NextResponse.json({ source: "sample", insight: rd.insight });
  }

  // ---- Build the analytics payload: real Instagram if connected, else sample.
  let analytics: unknown;
  let liveSource = "gemini";
  if (igConfigured()) {
    try {
      const snap = await fetchInstagramSnapshot();
      analytics = {
        data_source: "Instagram Graph API (live)",
        account: {
          username: snap.username,
          followers: snap.followers,
          posts_total: snap.mediaCount,
        },
        totals_recent_posts: snap.totals,
        recent_posts: snap.posts.slice(0, 15).map((p) => ({
          caption: p.caption.slice(0, 100),
          type: p.mediaType,
          date: p.timestamp,
          views: p.views,
          likes: p.likes,
          comments: p.comments,
          shares: p.shares,
          saved: p.saved,
          reach: p.reach,
        })),
      };
      liveSource = "instagram";
    } catch {
      analytics = sampleAnalytics(rd);
    }
  } else {
    analytics = sampleAnalytics(rd);
  }

  try {
    const parsed = await generateJson<Partial<AiInsight>>({
      system: SYSTEM,
      user:
        `Analytics (${liveSource === "instagram" ? "live Instagram" : rd.periodTitle.toLowerCase()}):\n` +
        `${JSON.stringify(analytics, null, 2)}\n\n` +
        "Produce a 1–2 sentence summary, exactly 3 specific observations, one pattern you detect, " +
        "one concrete recommended action for next period, and one metric to watch.",
      schema: SCHEMA,
    });

    const insight: AiInsight = {
      summary: parsed.summary ?? rd.insight.summary,
      observations: parsed.observations?.length
        ? parsed.observations
        : rd.insight.observations,
      pattern: parsed.pattern ?? rd.insight.pattern,
      action: parsed.action ?? rd.insight.action,
      watchMetric: parsed.watchMetric ?? rd.insight.watchMetric,
      generatedAt: new Date().toISOString(),
    };
    return NextResponse.json({ source: liveSource, insight });
  } catch (e) {
    return NextResponse.json({ source: "error", error: String(e), insight: rd.insight });
  }
}

function sampleAnalytics(rd: (typeof RANGE_DATA)[DashRange]) {
  return {
    data_source: "sample fixtures (not real)",
    period: rd.periodTitle,
    kpis: rd.kpis.map((k) => ({ metric: k.label, value: k.value, change: k.delta })),
    subscribers_now: rd.series[rd.series.length - 1]?.subscribers,
    timeseries: rd.series.map((p) => ({
      date: p.label,
      views: p.views,
      engagements: p.engagements,
      waitlist: p.waitlist,
      watch_through_pct: p.watchThru,
      subscribers: p.subscribers,
    })),
  };
}
